name: WisePlugin
main: com.github.wiseguy149.WisePlugin.WisePluginMain
version: 1
commands:
  stalk:
    description: Toggles whether or not to stalk a player.
    usage: /<command> [player]
    permission: <name>.stalk
    permission-message: You don't have permission <permission> to stalk anyone!